language: ruby
cache: bundler
rvm:
  - 3.2
  - 2.7
  - 2.6
gemfile:
  - Gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_6.gemfile
  - gemfiles/rails_6.1.gemfile
  - gemfiles/rails_7.gemfile
before_script:
  - bin/rails db:migrate RAILS_ENV=test
before_install:
  - gem install bundler
